const { Attendance, AttendanceAudit, Student, Faculty } = require('../models'); const { bulkMark, correct, authorizeSubject } = require('../services/attendanceService'); const { studentStats, subjectStats, lowAttendance } = require('../services/attendanceStats'); const AppError = require('../utils/AppError'); const { send } = require('../utils/response');
const profile = async (user) => Student.findOne({ userId: user._id });
exports.bulk = async (req, res) => send(res, 201, 'Attendance marked', await bulkMark(req.user, req.body));
exports.list = async (req, res) => { const query = {}; if (req.user.role === 'STUDENT') { const student = await profile(req.user); query.studentId = student?._id; } if (req.query.subjectId) { await authorizeSubject(req.user, req.query.subjectId); query.subjectId = req.query.subjectId; } const rows = await Attendance.find(query).populate('studentId subjectId facultyId').sort({ date: -1 }); send(res, 200, 'Attendance retrieved', rows); };
exports.get = async (req, res) => { const row = await Attendance.findById(req.params.id).populate('studentId subjectId facultyId'); if (!row) throw new AppError('Attendance record not found', 404); if (req.user.role === 'STUDENT' && String((await profile(req.user))._id) !== String(row.studentId._id)) throw new AppError('You do not have permission for this record', 403); if (req.user.role === 'FACULTY') await authorizeSubject(req.user, row.subjectId._id); send(res, 200, 'Attendance retrieved', row); };
exports.correct = async (req, res) => send(res, 200, 'Attendance corrected', await correct(req.user, req.params.id, req.body));
exports.student = async (req, res) => { let id = req.params.studentId; if (req.user.role === 'STUDENT') { const student = await profile(req.user); if (String(student?._id) !== id) throw new AppError('You can view only your own attendance', 403); } send(res, 200, 'Student attendance retrieved', { overall: await studentStats(id), subjects: await subjectStats(id), history: await Attendance.find({ studentId: id }).populate('subjectId').sort({ date: -1 }) }); };
exports.low = async (req, res) => { const faculty = req.user.role === 'FACULTY' ? await Faculty.findOne({ userId: req.user._id }) : null; if (req.user.role === 'FACULTY' && !faculty) throw new AppError('Faculty profile not found', 403); send(res, 200, 'Low-attendance students retrieved', await lowAttendance({ subjectId: req.query.subjectId, facultyId: faculty?._id })); };
exports.audit = async (req, res) => { const attendance = await Attendance.findById(req.params.attendanceId); if (!attendance) throw new AppError('Attendance record not found', 404); if (req.user.role === 'FACULTY') await authorizeSubject(req.user, attendance.subjectId); send(res, 200, 'Attendance audit retrieved', await AttendanceAudit.find({ attendanceId: attendance._id }).populate('changedBy', 'name email').sort({ changedAt: -1 })); };
