import { useEffect } from 'react';
export function Button({ children, variant = 'primary', className = '', ...props }) { return <button className={`button ${variant} ${className}`} {...props}>{children}</button>; }
export function Badge({ children, type = 'neutral' }) { return <span className={`badge ${type}`}>{children}</span>; }
export function Progress({ value }) { const hasValue = value !== null && value !== undefined; const safe = hasValue ? Math.max(0, Number(value) || 0) : 0; const tone = safe < 75 ? 'low' : safe < 90 ? 'okay' : 'good'; return <div className="progress-wrap" aria-label={hasValue ? `${safe}% attendance` : 'Attendance not yet available'}><div className={`progress ${tone}`} style={{ width: `${Math.min(safe, 100)}%` }} /></div>; }
export function Loading({ text = 'Loading…' }) { return <div className="state loading"><span className="spinner" />{text}</div>; }
export function ErrorMessage({ message, retry }) { return <div className="state error"><strong>Something went wrong.</strong><span>{message}</span>{retry && <Button variant="secondary" onClick={retry}>Try again</Button>}</div>; }
export function Empty({ title = 'Nothing here yet', description }) { return <div className="state empty"><strong>{title}</strong>{description && <span>{description}</span>}</div>; }
export function Modal({ title, children, onClose }) { useEffect(() => { const close = (e) => e.key === 'Escape' && onClose(); addEventListener('keydown', close); return () => removeEventListener('keydown', close); }, [onClose]); return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={(e) => e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog">×</button></div>{children}</section></div>; }
export function PageHeader({ title, description, action }) { return <header className="page-header"><div><p className="eyebrow">ATTENDX / WORKSPACE</p><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</header>; }
export function StatCard({ label, value, detail }) { return <article className="stat-card"><span>{label}</span><strong>{value}</strong>{detail && <small>{detail}</small>}</article>; }
